-- P5: atomic retraction/supersession propagation.
--
-- Single transaction (one plpgsql function -- atomic by Postgres function
-- semantics, no client-side multi-step orchestration) that: (1) marks the
-- source document retracted or superseded; (2) transitions its affected
-- active claims, and any cluster left with zero remaining active member
-- claims, out of active eligibility; (3) when the document was a
-- study-family primary (P4's duplicate_of_document_id target), auto-promotes
-- the fullest remaining non-retracted family member to primary using the
-- same fullness ranking src/lib/researchStudyFamily.ts already uses for
-- import-time matching (owner decision, 2026-08-02: auto-promote, not
-- manual-review-flag, not leave-orphaned); (4) the existing research_graph_*
-- views are live over these same tables, so eligibility disappears from the
-- projection immediately with no separate refresh step; (5) appends an
-- append-only audit/tombstone event naming the actor, reason, and every
-- affected identifier; (6) never deletes the original document, claim, or
-- cluster rows -- only status transitions and an audit trail, per this
-- project's provenance invariants.
--
-- "Corrected" and "superseded" share one mechanism here (p_action =
-- 'supersede', pointing research_documents.superseded_by at the replacement
-- document): the schema has never had a third state distinct from
-- retracted/superseded_by, and a correction is, mechanically, a document
-- being superseded by its corrected version. The reason text on the audit
-- event is what distinguishes "corrected" from "superseded by unrelated
-- follow-up work" -- there is no separate enum value to keep in sync.
--
-- A claim always belongs to exactly one document (research_claims.document_id),
-- so "affected claims" is exactly that document's active claims. A cluster is
-- only transitioned when NONE of its member claims remain active after this
-- change -- a cluster still independently supported by another document's
-- active claim must not be invalidated by an unrelated retraction.

-- Retire the two pre-P5 retraction mechanisms this function now subsumes and
-- makes safe to combine with supersession:
--
--   1. research_document_sync_claim_metadata (AFTER UPDATE OF ... retracted
--      ON research_documents, added by 20260728200000_research_claims_and_
--      grading.sql): fires synchronously the instant this function's own
--      document-retraction UPDATE runs, transitioning claims to 'superseded'
--      BEFORE this function's own explicit claim-transition step gets to
--      read "which claims were active." Left in place, it would silently
--      empty out affected_claim_ids on the audit event (the trigger already
--      did the work first) and it has no equivalent for the superseded_by
--      path at all, so retraction and supersession would behave
--      inconsistently. This function is now the single place that decides
--      and records which claims were affected.
--   2. mark_research_document_retracted (same migration): the retraction-
--      watch route now calls this function instead, which does everything
--      that one did (mark retracted) plus claim/cluster/study-family
--      propagation and an audit trail it never had.
--
-- Neither retirement touches research_claim_validate_and_sync (the
-- BEFORE INSERT/UPDATE literal-quote and retracted-active guard on
-- research_claims itself) -- that invariant is unrelated and stays.

drop trigger if exists research_document_sync_claim_metadata on public.research_documents;
drop function if exists public.sync_research_claims_after_document_change();
drop function if exists public.mark_research_document_retracted(uuid, timestamptz, text);

create table public.research_evidence_lifecycle_events (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.research_documents(id) on delete restrict,
  event_type text not null
    check (event_type in ('retracted', 'superseded')),
  reason text not null check (length(btrim(reason)) > 0),
  actor_type text not null default 'owner'
    check (actor_type in ('system', 'owner', 'worker')),
  actor_id uuid references auth.users(id) on delete set null,
  replacement_document_id uuid references public.research_documents(id) on delete set null,
  affected_claim_ids uuid[] not null default '{}'::uuid[],
  affected_cluster_ids uuid[] not null default '{}'::uuid[],
  promoted_primary_document_id uuid references public.research_documents(id) on delete set null,
  orphaned_duplicate_document_ids uuid[] not null default '{}'::uuid[],
  occurred_at timestamptz not null default now(),
  constraint research_evidence_lifecycle_events_owner_actor_check
    check (actor_type <> 'owner' or actor_id is not null),
  constraint research_evidence_lifecycle_events_replacement_check
    check (
      (event_type = 'superseded' and replacement_document_id is not null)
      or (event_type = 'retracted' and replacement_document_id is null)
    )
);

comment on table public.research_evidence_lifecycle_events
is 'Append-only tombstone/audit trail for P5 retraction and supersession propagation. Never updated or deleted -- see the append-only grants below. This is the audit-event mechanism for document lifecycle transitions; research_mission_events remains scoped to mission/stage/worker lifecycle and is not reused here.';
comment on column public.research_evidence_lifecycle_events.affected_claim_ids
is 'Claims that were status=active on this document immediately before this event and were transitioned to superseded by it.';
comment on column public.research_evidence_lifecycle_events.affected_cluster_ids
is 'Clusters transitioned to superseded because none of their member claims remained active after this event -- not every cluster touched, only those left with zero live support.';
comment on column public.research_evidence_lifecycle_events.promoted_primary_document_id
is 'When this document was a study-family primary (P4 duplicate_of_document_id target) with at least one non-retracted duplicate, the duplicate auto-promoted to primary using the same fullness ranking P4 uses at import time. Null when there was nothing to promote.';
comment on column public.research_evidence_lifecycle_events.orphaned_duplicate_document_ids
is 'Study-family duplicates of this document that could not be promoted because every one of them was also retracted. Surfaced for visibility, not auto-resolved.';

create index research_evidence_lifecycle_events_document_idx
  on public.research_evidence_lifecycle_events (document_id, occurred_at);

alter table public.research_evidence_lifecycle_events enable row level security;
revoke all on table public.research_evidence_lifecycle_events from public, anon, authenticated;
revoke all on table public.research_evidence_lifecycle_events from service_role;
grant select, insert on table public.research_evidence_lifecycle_events to service_role;
grant usage, select on sequence public.research_evidence_lifecycle_events_id_seq to service_role;

create or replace function public.propagate_research_document_status_change(
  p_document_id uuid,
  p_action text,
  p_replacement_document_id uuid,
  p_actor_id uuid,
  p_actor_type text,
  p_reason text
)
returns public.research_evidence_lifecycle_events
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_document public.research_documents;
  v_replacement public.research_documents;
  v_event_type text;
  v_affected_claim_ids uuid[];
  v_affected_cluster_ids uuid[];
  v_promoted_primary_document_id uuid;
  v_orphaned_duplicate_ids uuid[];
  v_event public.research_evidence_lifecycle_events;
begin
  if p_action not in ('retract', 'supersede') then
    raise exception 'Unsupported action: %', p_action;
  end if;
  if p_reason is null or length(btrim(p_reason)) = 0 then
    raise exception 'A reason is required to retract or supersede a research document';
  end if;
  if p_actor_type not in ('system', 'owner', 'worker') then
    raise exception 'Unsupported actor_type: %', p_actor_type;
  end if;
  if p_actor_type = 'owner' and p_actor_id is null then
    raise exception 'An owner actor requires an actor_id';
  end if;

  select * into v_document
  from public.research_documents
  where id = p_document_id
  for update;

  if not found then
    raise exception 'Research document % does not exist', p_document_id;
  end if;
  if v_document.retracted then
    raise exception 'Research document % is already retracted', p_document_id;
  end if;
  if v_document.superseded_by is not null then
    raise exception 'Research document % is already superseded', p_document_id;
  end if;

  if p_action = 'supersede' then
    if p_replacement_document_id is null then
      raise exception 'A replacement document is required to supersede a research document';
    end if;
    if p_replacement_document_id = p_document_id then
      raise exception 'A research document cannot supersede itself';
    end if;

    select * into v_replacement
    from public.research_documents
    where id = p_replacement_document_id
    for update;

    if not found then
      raise exception 'Replacement research document % does not exist', p_replacement_document_id;
    end if;
    if v_replacement.retracted or v_replacement.superseded_by is not null then
      raise exception 'Replacement research document % is not itself eligible (retracted or superseded)', p_replacement_document_id;
    end if;

    v_event_type := 'superseded';
  else
    if p_replacement_document_id is not null then
      raise exception 'A retraction may not specify a replacement document';
    end if;
    v_event_type := 'retracted';
  end if;

  -- Step 1: mark the source document.
  if p_action = 'retract' then
    update public.research_documents
    set retracted = true, retraction_checked_at = now()
    where id = p_document_id;
  else
    update public.research_documents
    set superseded_by = p_replacement_document_id
    where id = p_document_id;
  end if;

  -- Step 2: transition this document's currently-active claims out of eligibility.
  select coalesce(array_agg(id), '{}'::uuid[]) into v_affected_claim_ids
  from public.research_claims
  where document_id = p_document_id and status = 'active';

  update public.research_claims
  set status = 'superseded'
  where document_id = p_document_id and status = 'active';

  -- Step 3: transition any active cluster left with zero remaining active
  -- member claims. A cluster still independently supported by another
  -- document's active claim is untouched.
  select coalesce(array_agg(c.id), '{}'::uuid[]) into v_affected_cluster_ids
  from public.research_evidence_clusters c
  where c.status = 'active'
    and exists (
      select 1
      from public.research_evidence_cluster_members m
      where m.cluster_id = c.id and m.claim_id = any(v_affected_claim_ids)
    )
    and not exists (
      select 1
      from public.research_evidence_cluster_members m
      join public.research_claims rc on rc.id = m.claim_id
      where m.cluster_id = c.id and rc.status = 'active'
    );

  update public.research_evidence_clusters
  set status = 'superseded'
  where id = any(v_affected_cluster_ids);

  -- Step 4: study-family corroboration propagation. Only relevant when this
  -- document was a primary (P4 duplicate_of_document_id target) with at
  -- least one duplicate pointing at it. Candidates for promotion are never
  -- claims-bearing (P4's processing route excludes duplicate-flagged
  -- documents from the claim-drafting queue), so re-pointing them here never
  -- touches the "immutable once claims exist" invariant.
  v_promoted_primary_document_id := null;
  v_orphaned_duplicate_ids := '{}'::uuid[];

  if exists (
    select 1 from public.research_documents where duplicate_of_document_id = p_document_id
  ) then
    select id into v_promoted_primary_document_id
    from public.research_documents
    where duplicate_of_document_id = p_document_id
      and retracted = false
    order by
      (
        case when not coalesce(abstract_only, false) then 2 else 0 end
        + case when not coalesce(is_preprint, false) then 2 else 0 end
        + coalesce(
            case evidence_grade
              when 'A' then 4
              when 'B' then 3
              when 'C' then 2
              when 'D' then 1
              when 'E' then 0
            end,
            0
          )
      ) desc,
      duplicate_detected_at asc nulls last,
      id asc
    limit 1;

    if v_promoted_primary_document_id is not null then
      -- Promote first (clears its own duplicate_of_document_id so it
      -- qualifies as a primary target for the next statement, per
      -- enforce_research_document_duplicate_target's no-chains rule).
      update public.research_documents
      set duplicate_of_document_id = null
      where id = v_promoted_primary_document_id;

      update public.research_documents
      set duplicate_of_document_id = v_promoted_primary_document_id
      where duplicate_of_document_id = p_document_id
        and id <> v_promoted_primary_document_id;
    else
      select coalesce(array_agg(id), '{}'::uuid[]) into v_orphaned_duplicate_ids
      from public.research_documents
      where duplicate_of_document_id = p_document_id;
    end if;
  end if;

  -- Step 5: append-only tombstone/audit event. Never updated or deleted.
  insert into public.research_evidence_lifecycle_events (
    document_id, event_type, reason, actor_type, actor_id,
    replacement_document_id, affected_claim_ids, affected_cluster_ids,
    promoted_primary_document_id, orphaned_duplicate_document_ids
  ) values (
    p_document_id, v_event_type, p_reason, p_actor_type, p_actor_id,
    p_replacement_document_id, v_affected_claim_ids, v_affected_cluster_ids,
    v_promoted_primary_document_id, v_orphaned_duplicate_ids
  )
  returning * into v_event;

  return v_event;
end;
$function$;

comment on function public.propagate_research_document_status_change(uuid, text, uuid, uuid, text, text)
is 'P5 atomic retraction/supersession propagation. Single plpgsql function so a failure at any step rolls back every step (document status, claim/cluster transitions, study-family promotion, audit event) by ordinary Postgres transaction semantics. Callable only by the service role used by server-side admin/retraction-watch routes.';

revoke all on function public.propagate_research_document_status_change(uuid, text, uuid, uuid, text, text) from public, anon, authenticated;
grant execute on function public.propagate_research_document_status_change(uuid, text, uuid, uuid, text, text) to service_role;

-- Graph projection: SUPERSEDES and RETRACTED_BY, deferred to P5 explicitly by
-- 20260802170000_research_graph_projection.sql's own comment ("A retracted/
-- superseded document has no node in this projection at all ... belongs to
-- whichever phase defines it"). Both are tombstone edges by necessity: the
-- old/retracted side is never itself an eligible research_graph_documents
-- node (that is the point of retraction), so unlike P4's SAME_STUDY_FAMILY
-- edge (which requires both endpoints to be eligible nodes), only the
-- "still-live" side of each of these edges is required to resolve to a node.
--
-- SUPERSEDES connects the new/replacement document (must be an eligible
-- node) back to the old, tombstoned document (by raw id, never a node).
-- RETRACTED_BY has no replacement document to point to for a pure retraction,
-- so it terminates at the audit event instead (reason/actor/timestamp) rather
-- than at another document. This edge-shape choice is a graph-presentation
-- decision, not a product-policy one; flagged here for owner review like any
-- other durable technical choice, not gated on it.

create or replace view public.research_graph_edges_supersedes
with (security_invoker = true) as
select
  'SUPERSEDES'::text as edge_type,
  d.document_id as new_document_id,
  rd.id as old_document_id,
  rd.title as old_document_title,
  e.reason,
  e.occurred_at
from public.research_documents rd
join public.research_graph_documents d on d.document_id = rd.superseded_by
left join public.research_evidence_lifecycle_events e
  on e.document_id = rd.id and e.event_type = 'superseded'
where rd.superseded_by is not null;

comment on view public.research_graph_edges_supersedes
is 'P5 graph edge: new document SUPERSEDES old (tombstoned) document. Only the new/replacement side must be an eligible research_graph_documents node.';

create or replace view public.research_graph_edges_retracted_by
with (security_invoker = true) as
select
  'RETRACTED_BY'::text as edge_type,
  rd.id as document_id,
  rd.title as document_title,
  e.id as lifecycle_event_id,
  e.reason,
  e.actor_type,
  e.occurred_at
from public.research_documents rd
join public.research_evidence_lifecycle_events e
  on e.document_id = rd.id and e.event_type = 'retracted'
where rd.retracted = true
  and rd.superseded_by is null;

comment on view public.research_graph_edges_retracted_by
is 'P5 graph edge: retracted document RETRACTED_BY its lifecycle/audit event. A pure retraction has no replacement document, so the tombstone edge terminates at the audit event (reason/actor/timestamp) rather than at another document.';

revoke all on public.research_graph_edges_supersedes from public, anon, authenticated;
revoke all on public.research_graph_edges_retracted_by from public, anon, authenticated;
grant select on public.research_graph_edges_supersedes to service_role;
grant select on public.research_graph_edges_retracted_by to service_role;
