-- Research mission lifecycle and durable audit events.
--
-- This is an additive control-plane layer over research_ingestion_jobs. It does
-- not backfill or reinterpret existing jobs, documents, claims, clusters, review
-- decisions, recommendation evidence, or runtime ranking. New server-side
-- operations create a mission, one stage attempt, and the existing executable
-- job atomically through service-role-only functions.

create table public.research_missions (
  id uuid primary key default gen_random_uuid(),
  mission_type text not null
    check (mission_type in (
      'discovery',
      'source_import',
      'document_processing',
      'claim_drafting',
      'clustering',
      'review_handoff'
    )),
  objective text not null check (length(btrim(objective)) > 0),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'completed', 'partial', 'failed', 'cancelled')),
  requested_by uuid not null references auth.users(id) on delete restrict,
  input jsonb not null default '{}'::jsonb
    check (jsonb_typeof(input) = 'object'),
  result_summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(result_summary) = 'object'),
  current_stage_key text,
  terminal_reason_code text,
  terminal_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint research_missions_reason_code_check
    check (
      terminal_reason_code is null
      or terminal_reason_code ~ '^[a-z][a-z0-9_]*$'
    ),
  constraint research_missions_terminal_reason_check
    check (
      status not in ('partial', 'failed', 'cancelled')
      or length(btrim(coalesce(terminal_reason_code, ''))) > 0
    ),
  constraint research_missions_running_time_check
    check (status <> 'running' or started_at is not null),
  constraint research_missions_completed_time_check
    check (
      (status in ('completed', 'partial', 'failed', 'cancelled') and completed_at is not null)
      or (status in ('queued', 'running') and completed_at is null)
    )
);

create table public.research_mission_stages (
  id uuid primary key default gen_random_uuid(),
  mission_id uuid not null references public.research_missions(id) on delete restrict,
  stage_key text not null
    check (stage_key in (
      'discovery',
      'source_acquisition',
      'document_ingestion',
      'relevance_selection',
      'claim_drafting',
      'clustering',
      'review_handoff'
    )),
  attempt_number smallint not null default 1 check (attempt_number > 0),
  retry_of_stage_id uuid references public.research_mission_stages(id) on delete restrict,
  status text not null default 'pending'
    check (status in ('pending', 'running', 'succeeded', 'partial', 'failed', 'skipped', 'cancelled')),
  idempotency_key text,
  input jsonb not null default '{}'::jsonb
    check (jsonb_typeof(input) = 'object'),
  result_summary jsonb not null default '{}'::jsonb
    check (jsonb_typeof(result_summary) = 'object'),
  reason_code text,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint research_mission_stages_attempt_key
    unique (mission_id, stage_key, attempt_number),
  constraint research_mission_stages_idempotency_key_check
    check (idempotency_key is null or length(btrim(idempotency_key)) > 0),
  constraint research_mission_stages_reason_code_check
    check (reason_code is null or reason_code ~ '^[a-z][a-z0-9_]*$'),
  constraint research_mission_stages_terminal_reason_check
    check (
      status not in ('partial', 'failed', 'skipped', 'cancelled')
      or length(btrim(coalesce(reason_code, ''))) > 0
    ),
  constraint research_mission_stages_retry_check
    check (
      (attempt_number = 1 and retry_of_stage_id is null)
      or (attempt_number > 1 and retry_of_stage_id is not null)
    ),
  constraint research_mission_stages_running_time_check
    check (status <> 'running' or started_at is not null),
  constraint research_mission_stages_completed_time_check
    check (
      (status in ('succeeded', 'partial', 'failed', 'skipped', 'cancelled') and completed_at is not null)
      or (status in ('pending', 'running') and completed_at is null)
    )
);

create unique index research_mission_stages_idempotency_idx
  on public.research_mission_stages (idempotency_key)
  where idempotency_key is not null;
create index research_mission_stages_mission_idx
  on public.research_mission_stages (mission_id, created_at, attempt_number);
create index research_mission_stages_retry_idx
  on public.research_mission_stages (retry_of_stage_id)
  where retry_of_stage_id is not null;

create table public.research_mission_events (
  id bigint generated by default as identity primary key,
  mission_id uuid not null references public.research_missions(id) on delete restrict,
  mission_stage_id uuid references public.research_mission_stages(id) on delete restrict,
  sequence_number bigint not null check (sequence_number > 0),
  event_type text not null
    check (event_type ~ '^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)+$'),
  actor_type text not null default 'worker'
    check (actor_type in ('system', 'owner', 'worker')),
  actor_id uuid references auth.users(id) on delete set null,
  payload jsonb not null default '{}'::jsonb
    check (jsonb_typeof(payload) = 'object'),
  occurred_at timestamptz not null default now(),
  constraint research_mission_events_sequence_key unique (mission_id, sequence_number),
  constraint research_mission_events_owner_actor_check
    check (actor_type <> 'owner' or actor_id is not null)
);

create index research_mission_events_mission_idx
  on public.research_mission_events (mission_id, sequence_number);
create index research_mission_events_stage_idx
  on public.research_mission_events (mission_stage_id, sequence_number)
  where mission_stage_id is not null;
create index research_missions_status_idx
  on public.research_missions (status, created_at desc);
create index research_missions_requester_idx
  on public.research_missions (requested_by, created_at desc);

alter table public.research_ingestion_jobs
  add column mission_id uuid references public.research_missions(id) on delete set null,
  add column mission_stage_id uuid references public.research_mission_stages(id) on delete set null;

create index research_ingestion_jobs_mission_idx
  on public.research_ingestion_jobs (mission_id, created_at desc)
  where mission_id is not null;
create unique index research_ingestion_jobs_mission_stage_idx
  on public.research_ingestion_jobs (mission_stage_id)
  where mission_stage_id is not null;

create or replace function public.touch_research_mission_lifecycle_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger research_missions_touch_updated_at
before update on public.research_missions
for each row execute function public.touch_research_mission_lifecycle_updated_at();

create trigger research_mission_stages_touch_updated_at
before update on public.research_mission_stages
for each row execute function public.touch_research_mission_lifecycle_updated_at();

create or replace function public.prevent_research_mission_identity_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (
    new.id is distinct from old.id
    or new.mission_type is distinct from old.mission_type
    or new.objective is distinct from old.objective
    or new.requested_by is distinct from old.requested_by
    or new.input is distinct from old.input
    or new.created_at is distinct from old.created_at
  ) then
    raise exception 'Research mission identity and input are immutable';
  end if;
  return new;
end;
$$;

create or replace function public.prevent_research_mission_stage_identity_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if (
    new.id is distinct from old.id
    or new.mission_id is distinct from old.mission_id
    or new.stage_key is distinct from old.stage_key
    or new.attempt_number is distinct from old.attempt_number
    or new.retry_of_stage_id is distinct from old.retry_of_stage_id
    or new.idempotency_key is distinct from old.idempotency_key
    or new.input is distinct from old.input
    or new.created_at is distinct from old.created_at
  ) then
    raise exception 'Research mission stage identity and input are immutable';
  end if;
  return new;
end;
$$;

create trigger research_missions_identity_immutable
before update on public.research_missions
for each row execute function public.prevent_research_mission_identity_mutation();

create trigger research_mission_stages_identity_immutable
before update on public.research_mission_stages
for each row execute function public.prevent_research_mission_stage_identity_mutation();

create or replace function public.validate_research_mission_stage_retry()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  previous_stage public.research_mission_stages%rowtype;
begin
  if new.retry_of_stage_id is null then
    return new;
  end if;

  select *
  into previous_stage
  from public.research_mission_stages
  where id = new.retry_of_stage_id;

  if previous_stage.id is null
    or previous_stage.mission_id <> new.mission_id
    or previous_stage.stage_key <> new.stage_key
    or previous_stage.attempt_number >= new.attempt_number then
    raise exception 'Retry stage must reference an earlier attempt of the same mission stage';
  end if;

  return new;
end;
$$;

create trigger research_mission_stage_retry_validate
before insert or update of mission_id, stage_key, attempt_number, retry_of_stage_id
on public.research_mission_stages
for each row execute function public.validate_research_mission_stage_retry();

create or replace function public.validate_research_ingestion_job_mission_links()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  linked_mission_id uuid;
begin
  if tg_op = 'UPDATE'
    and old.mission_id is not null
    and (
      new.mission_id is distinct from old.mission_id
      or new.mission_stage_id is distinct from old.mission_stage_id
    ) then
    raise exception 'Research ingestion job mission links are immutable once assigned';
  end if;

  if new.mission_id is null and new.mission_stage_id is null then
    return new;
  end if;
  if new.mission_id is null or new.mission_stage_id is null then
    raise exception 'Mission and mission stage links must both be set or both be null';
  end if;

  select mission_id
  into linked_mission_id
  from public.research_mission_stages
  where id = new.mission_stage_id;

  if linked_mission_id is null or linked_mission_id <> new.mission_id then
    raise exception 'Research ingestion job stage does not belong to its mission';
  end if;
  return new;
end;
$$;

create trigger research_ingestion_job_mission_links_validate
before insert or update of mission_id, mission_stage_id
on public.research_ingestion_jobs
for each row execute function public.validate_research_ingestion_job_mission_links();

create or replace function public.prevent_research_mission_event_mutation()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  raise exception 'Research mission events are append-only';
end;
$$;

create trigger research_mission_events_immutable
before update or delete on public.research_mission_events
for each row execute function public.prevent_research_mission_event_mutation();

create or replace function public.append_research_mission_event(
  p_mission_id uuid,
  p_mission_stage_id uuid,
  p_event_type text,
  p_actor_type text default 'worker',
  p_actor_id uuid default null,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  next_sequence bigint;
  inserted_id bigint;
  linked_mission_id uuid;
begin
  if not exists (select 1 from public.research_missions where id = p_mission_id) then
    raise exception 'Research mission not found';
  end if;

  if p_mission_stage_id is not null then
    select mission_id
    into linked_mission_id
    from public.research_mission_stages
    where id = p_mission_stage_id;
    if linked_mission_id is null or linked_mission_id <> p_mission_id then
      raise exception 'Research mission event stage does not belong to mission';
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_mission_id::text, 0));
  select coalesce(max(sequence_number), 0) + 1
  into next_sequence
  from public.research_mission_events
  where mission_id = p_mission_id;

  insert into public.research_mission_events (
    mission_id,
    mission_stage_id,
    sequence_number,
    event_type,
    actor_type,
    actor_id,
    payload
  ) values (
    p_mission_id,
    p_mission_stage_id,
    next_sequence,
    p_event_type,
    p_actor_type,
    p_actor_id,
    coalesce(p_payload, '{}'::jsonb)
  )
  returning id into inserted_id;

  return inserted_id;
end;
$$;

create or replace function public.start_research_mission_job(
  p_mission_type text,
  p_objective text,
  p_stage_key text,
  p_job_type text,
  p_requested_by uuid,
  p_input jsonb default '{}'::jsonb,
  p_initial_status text default 'running',
  p_gateway_model text default null,
  p_idempotency_key text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  new_mission public.research_missions%rowtype;
  new_stage public.research_mission_stages%rowtype;
  new_job public.research_ingestion_jobs%rowtype;
  existing_job public.research_ingestion_jobs%rowtype;
  started_time timestamptz;
begin
  if p_initial_status not in ('queued', 'running') then
    raise exception 'Initial research mission job status must be queued or running';
  end if;
  if jsonb_typeof(coalesce(p_input, '{}'::jsonb)) <> 'object' then
    raise exception 'Research mission input must be a JSON object';
  end if;

  if p_idempotency_key is not null then
    perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 1));
    select job.*
    into existing_job
    from public.research_mission_stages stage
    join public.research_ingestion_jobs job on job.mission_stage_id = stage.id
    where stage.idempotency_key = p_idempotency_key;
    if existing_job.id is not null then
      if existing_job.requested_by <> p_requested_by
        or existing_job.job_type <> p_job_type
        or existing_job.input <> coalesce(p_input, '{}'::jsonb)
        or not exists (
          select 1
          from public.research_mission_stages stage
          join public.research_missions mission on mission.id = stage.mission_id
          where stage.id = existing_job.mission_stage_id
            and stage.stage_key = p_stage_key
            and mission.mission_type = p_mission_type
        ) then
        raise exception 'Research mission idempotency key was reused for different input';
      end if;
      return to_jsonb(existing_job);
    end if;
  end if;

  started_time := case when p_initial_status = 'running' then now() else null end;

  insert into public.research_missions (
    mission_type,
    objective,
    status,
    requested_by,
    input,
    current_stage_key,
    started_at
  ) values (
    p_mission_type,
    p_objective,
    p_initial_status,
    p_requested_by,
    coalesce(p_input, '{}'::jsonb),
    p_stage_key,
    started_time
  )
  returning * into new_mission;

  insert into public.research_mission_stages (
    mission_id,
    stage_key,
    status,
    idempotency_key,
    input,
    started_at
  ) values (
    new_mission.id,
    p_stage_key,
    case when p_initial_status = 'running' then 'running' else 'pending' end,
    p_idempotency_key,
    coalesce(p_input, '{}'::jsonb),
    started_time
  )
  returning * into new_stage;

  insert into public.research_ingestion_jobs (
    job_type,
    status,
    requested_by,
    input,
    gateway_model,
    started_at,
    mission_id,
    mission_stage_id
  ) values (
    p_job_type,
    p_initial_status,
    p_requested_by,
    coalesce(p_input, '{}'::jsonb),
    p_gateway_model,
    started_time,
    new_mission.id,
    new_stage.id
  )
  returning * into new_job;

  perform public.append_research_mission_event(
    new_mission.id,
    null,
    'mission.created',
    'owner',
    p_requested_by,
    jsonb_build_object(
      'mission_type', p_mission_type,
      'status', p_initial_status,
      'job_id', new_job.id
    )
  );
  perform public.append_research_mission_event(
    new_mission.id,
    new_stage.id,
    case when p_initial_status = 'running' then 'stage.started' else 'stage.queued' end,
    'owner',
    p_requested_by,
    jsonb_build_object(
      'stage_key', p_stage_key,
      'attempt_number', 1,
      'job_id', new_job.id
    )
  );

  return to_jsonb(new_job);
end;
$$;

create or replace function public.mark_research_mission_job_running(
  p_job_id uuid,
  p_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  linked_job public.research_ingestion_jobs%rowtype;
  linked_mission public.research_missions%rowtype;
  started_time timestamptz := now();
begin
  select * into linked_job
  from public.research_ingestion_jobs
  where id = p_job_id
  for update;

  if linked_job.id is null or linked_job.mission_id is null or linked_job.mission_stage_id is null then
    raise exception 'Linked research mission job not found';
  end if;
  if linked_job.status = 'running' then
    return to_jsonb(linked_job);
  end if;
  if linked_job.status <> 'queued' then
    raise exception 'Only queued research mission jobs can start running';
  end if;

  select * into linked_mission
  from public.research_missions
  where id = linked_job.mission_id
  for update;

  update public.research_ingestion_jobs
  set status = 'running', started_at = started_time, updated_at = started_time
  where id = p_job_id
  returning * into linked_job;

  update public.research_mission_stages
  set status = 'running', started_at = started_time
  where id = linked_job.mission_stage_id;

  update public.research_missions
  set status = 'running', started_at = coalesce(started_at, started_time)
  where id = linked_job.mission_id;

  if linked_mission.status = 'queued' then
    perform public.append_research_mission_event(
      linked_job.mission_id,
      null,
      'mission.started',
      'worker',
      null,
      jsonb_build_object('job_id', linked_job.id)
    );
  end if;
  perform public.append_research_mission_event(
    linked_job.mission_id,
    linked_job.mission_stage_id,
    'stage.started',
    'worker',
    null,
    jsonb_build_object('job_id', linked_job.id) || coalesce(p_payload, '{}'::jsonb)
  );

  return to_jsonb(linked_job);
end;
$$;

create or replace function public.retry_research_mission_job_stage(
  p_failed_job_id uuid,
  p_requested_by uuid,
  p_idempotency_key text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  failed_job public.research_ingestion_jobs%rowtype;
  failed_stage public.research_mission_stages%rowtype;
  linked_mission public.research_missions%rowtype;
  retry_stage public.research_mission_stages%rowtype;
  retry_job public.research_ingestion_jobs%rowtype;
  existing_job public.research_ingestion_jobs%rowtype;
  next_attempt smallint;
begin
  if p_idempotency_key is not null then
    perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 2));
  end if;

  select * into failed_job
  from public.research_ingestion_jobs
  where id = p_failed_job_id
  for update;
  if failed_job.id is null
    or failed_job.status <> 'failed'
    or failed_job.mission_id is null
    or failed_job.mission_stage_id is null then
    raise exception 'Only a failed linked research mission job can be retried';
  end if;

  select * into failed_stage
  from public.research_mission_stages
  where id = failed_job.mission_stage_id
  for update;
  if failed_stage.id is null or failed_stage.status <> 'failed' then
    raise exception 'Failed research mission stage not found';
  end if;

  select * into linked_mission
  from public.research_missions
  where id = failed_job.mission_id
  for update;
  if linked_mission.id is null or linked_mission.requested_by <> p_requested_by then
    raise exception 'Research mission retry requester does not match mission owner';
  end if;

  if p_idempotency_key is not null then
    select job.*
    into existing_job
    from public.research_mission_stages stage
    join public.research_ingestion_jobs job on job.mission_stage_id = stage.id
    where stage.idempotency_key = p_idempotency_key;
    if existing_job.id is not null then
      if existing_job.requested_by <> p_requested_by
        or not exists (
          select 1
          from public.research_mission_stages stage
          where stage.id = existing_job.mission_stage_id
            and stage.retry_of_stage_id = failed_stage.id
        ) then
        raise exception 'Research retry idempotency key was reused for a different attempt';
      end if;
      return to_jsonb(existing_job);
    end if;
  end if;

  select job.*
  into existing_job
  from public.research_mission_stages stage
  join public.research_ingestion_jobs job on job.mission_stage_id = stage.id
  where stage.retry_of_stage_id = failed_stage.id
  order by stage.attempt_number desc
  limit 1;
  if existing_job.id is not null then
    return to_jsonb(existing_job);
  end if;

  select (coalesce(max(attempt_number), 0) + 1)::smallint
  into next_attempt
  from public.research_mission_stages
  where mission_id = failed_stage.mission_id
    and stage_key = failed_stage.stage_key;

  insert into public.research_mission_stages (
    mission_id,
    stage_key,
    attempt_number,
    retry_of_stage_id,
    status,
    idempotency_key,
    input
  ) values (
    failed_stage.mission_id,
    failed_stage.stage_key,
    next_attempt,
    failed_stage.id,
    'pending',
    p_idempotency_key,
    failed_job.input
  )
  returning * into retry_stage;

  insert into public.research_ingestion_jobs (
    job_type,
    status,
    requested_by,
    input,
    gateway_model,
    mission_id,
    mission_stage_id
  ) values (
    failed_job.job_type,
    'queued',
    p_requested_by,
    failed_job.input,
    failed_job.gateway_model,
    failed_job.mission_id,
    retry_stage.id
  )
  returning * into retry_job;

  update public.research_missions
  set
    status = 'queued',
    current_stage_key = failed_stage.stage_key,
    result_summary = '{}'::jsonb,
    terminal_reason_code = null,
    terminal_message = null,
    completed_at = null
  where id = failed_job.mission_id;

  perform public.append_research_mission_event(
    failed_job.mission_id,
    retry_stage.id,
    'stage.retry_queued',
    'owner',
    p_requested_by,
    jsonb_build_object(
      'job_id', retry_job.id,
      'retry_of_job_id', failed_job.id,
      'retry_of_stage_id', failed_stage.id,
      'attempt_number', next_attempt
    )
  );
  perform public.append_research_mission_event(
    failed_job.mission_id,
    null,
    'mission.retry_queued',
    'owner',
    p_requested_by,
    jsonb_build_object(
      'job_id', retry_job.id,
      'retry_of_job_id', failed_job.id,
      'stage_key', failed_stage.stage_key,
      'attempt_number', next_attempt
    )
  );

  return to_jsonb(retry_job);
end;
$$;

create or replace function public.finish_research_mission_job(
  p_job_id uuid,
  p_job_status text,
  p_result_summary jsonb default null,
  p_reason_code text default null,
  p_error_message text default null,
  p_gateway_model text default null,
  p_gateway_input_tokens bigint default null,
  p_gateway_output_tokens bigint default null,
  p_gateway_cost_usd numeric default null,
  p_event_payload jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  linked_job public.research_ingestion_jobs%rowtype;
  finished_time timestamptz := now();
  stage_status text;
  mission_status text;
  stage_event_type text;
  mission_event_type text;
begin
  if p_job_status not in ('awaiting_selection', 'succeeded', 'failed') then
    raise exception 'Unsupported terminal research ingestion job status';
  end if;
  if p_job_status = 'failed' and length(btrim(coalesce(p_reason_code, ''))) = 0 then
    raise exception 'A deterministic reason code is required for failed research mission jobs';
  end if;
  if p_job_status = 'failed' and length(btrim(coalesce(p_error_message, ''))) = 0 then
    raise exception 'An error message is required for failed research mission jobs';
  end if;
  if p_result_summary is not null and jsonb_typeof(p_result_summary) <> 'object' then
    raise exception 'Research mission result summary must be a JSON object';
  end if;

  select * into linked_job
  from public.research_ingestion_jobs
  where id = p_job_id
  for update;

  if linked_job.id is null or linked_job.mission_id is null or linked_job.mission_stage_id is null then
    raise exception 'Linked research mission job not found';
  end if;
  if linked_job.status = p_job_status then
    return to_jsonb(linked_job);
  end if;
  if linked_job.status not in ('queued', 'running') then
    raise exception 'Research mission job is already terminal';
  end if;

  stage_status := case when p_job_status = 'failed' then 'failed' else 'succeeded' end;
  mission_status := case when p_job_status = 'failed' then 'failed' else 'completed' end;
  stage_event_type := case when p_job_status = 'failed' then 'stage.failed' else 'stage.succeeded' end;
  mission_event_type := case when p_job_status = 'failed' then 'mission.failed' else 'mission.completed' end;

  update public.research_ingestion_jobs
  set
    status = p_job_status,
    result_summary = coalesce(p_result_summary, result_summary),
    error_message = case when p_job_status = 'failed' then p_error_message else null end,
    gateway_model = coalesce(p_gateway_model, gateway_model),
    gateway_input_tokens = coalesce(p_gateway_input_tokens, gateway_input_tokens),
    gateway_output_tokens = coalesce(p_gateway_output_tokens, gateway_output_tokens),
    gateway_cost_usd = coalesce(p_gateway_cost_usd, gateway_cost_usd),
    started_at = coalesce(started_at, finished_time),
    completed_at = finished_time,
    updated_at = finished_time
  where id = p_job_id
  returning * into linked_job;

  update public.research_mission_stages
  set
    status = stage_status,
    result_summary = coalesce(p_result_summary, result_summary),
    reason_code = case when p_job_status = 'failed' then p_reason_code else null end,
    error_message = case when p_job_status = 'failed' then p_error_message else null end,
    started_at = coalesce(started_at, finished_time),
    completed_at = finished_time
  where id = linked_job.mission_stage_id;

  update public.research_missions
  set
    status = mission_status,
    result_summary = coalesce(p_result_summary, result_summary),
    terminal_reason_code = case when p_job_status = 'failed' then p_reason_code else null end,
    terminal_message = case when p_job_status = 'failed' then p_error_message else null end,
    started_at = coalesce(started_at, finished_time),
    completed_at = finished_time
  where id = linked_job.mission_id;

  perform public.append_research_mission_event(
    linked_job.mission_id,
    linked_job.mission_stage_id,
    stage_event_type,
    'worker',
    null,
    jsonb_build_object(
      'job_id', linked_job.id,
      'job_status', p_job_status,
      'reason_code', p_reason_code
    ) || coalesce(p_event_payload, '{}'::jsonb)
  );
  perform public.append_research_mission_event(
    linked_job.mission_id,
    null,
    mission_event_type,
    'worker',
    null,
    jsonb_build_object(
      'job_id', linked_job.id,
      'status', mission_status,
      'reason_code', p_reason_code
    )
  );

  return to_jsonb(linked_job);
end;
$$;

create or replace function public.append_research_mission_job_event(
  p_job_id uuid,
  p_event_type text,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security invoker
set search_path = ''
as $$
declare
  linked_job public.research_ingestion_jobs%rowtype;
begin
  select * into linked_job
  from public.research_ingestion_jobs
  where id = p_job_id;
  if linked_job.id is null or linked_job.mission_id is null or linked_job.mission_stage_id is null then
    raise exception 'Linked research mission job not found';
  end if;
  return public.append_research_mission_event(
    linked_job.mission_id,
    linked_job.mission_stage_id,
    p_event_type,
    'worker',
    null,
    jsonb_build_object('job_id', linked_job.id) || coalesce(p_payload, '{}'::jsonb)
  );
end;
$$;

alter table public.research_missions enable row level security;
alter table public.research_mission_stages enable row level security;
alter table public.research_mission_events enable row level security;

revoke all on table public.research_missions from anon, authenticated;
revoke all on table public.research_mission_stages from anon, authenticated;
revoke all on table public.research_mission_events from anon, authenticated;
revoke all on table public.research_missions from service_role;
revoke all on table public.research_mission_stages from service_role;
grant select, insert, update on table public.research_missions to service_role;
grant select, insert, update on table public.research_mission_stages to service_role;
revoke all on table public.research_mission_events from service_role;
grant select, insert on table public.research_mission_events to service_role;
grant usage, select on sequence public.research_mission_events_id_seq to service_role;

create policy "service role manages research missions"
  on public.research_missions for all to service_role
  using (true) with check (true);
create policy "service role manages research mission stages"
  on public.research_mission_stages for all to service_role
  using (true) with check (true);
create policy "service role reads research mission events"
  on public.research_mission_events for select to service_role
  using (true);
create policy "service role appends research mission events"
  on public.research_mission_events for insert to service_role
  with check (true);

revoke execute on function public.touch_research_mission_lifecycle_updated_at() from public, anon, authenticated;
revoke execute on function public.prevent_research_mission_identity_mutation() from public, anon, authenticated;
revoke execute on function public.prevent_research_mission_stage_identity_mutation() from public, anon, authenticated;
revoke execute on function public.validate_research_mission_stage_retry() from public, anon, authenticated;
revoke execute on function public.validate_research_ingestion_job_mission_links() from public, anon, authenticated;
revoke execute on function public.prevent_research_mission_event_mutation() from public, anon, authenticated;
revoke execute on function public.append_research_mission_event(uuid, uuid, text, text, uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.start_research_mission_job(text, text, text, text, uuid, jsonb, text, text, text) from public, anon, authenticated;
revoke execute on function public.mark_research_mission_job_running(uuid, jsonb) from public, anon, authenticated;
revoke execute on function public.retry_research_mission_job_stage(uuid, uuid, text) from public, anon, authenticated;
revoke execute on function public.finish_research_mission_job(uuid, text, jsonb, text, text, text, bigint, bigint, numeric, jsonb) from public, anon, authenticated;
revoke execute on function public.append_research_mission_job_event(uuid, text, jsonb) from public, anon, authenticated;

grant execute on function public.append_research_mission_event(uuid, uuid, text, text, uuid, jsonb) to service_role;
grant execute on function public.start_research_mission_job(text, text, text, text, uuid, jsonb, text, text, text) to service_role;
grant execute on function public.mark_research_mission_job_running(uuid, jsonb) to service_role;
grant execute on function public.retry_research_mission_job_stage(uuid, uuid, text) to service_role;
grant execute on function public.finish_research_mission_job(uuid, text, jsonb, text, text, text, bigint, bigint, numeric, jsonb) to service_role;
grant execute on function public.append_research_mission_job_event(uuid, text, jsonb) to service_role;

comment on table public.research_missions
is 'Parent control-plane records for bounded research operations. Missions never run in recommendation requests and do not confer evidence approval.';
comment on table public.research_mission_stages
is 'Immutable-attempt history for mission stages. Retries use a new row linked to the prior attempt; they never overwrite the failed attempt.';
comment on table public.research_mission_events
is 'Append-only, replayable mission progress and audit events. Polling reads this persisted log; no process-memory event stream is authoritative.';
comment on column public.research_ingestion_jobs.mission_id
is 'Nullable parent mission link. Legacy jobs remain null and unchanged.';
comment on column public.research_ingestion_jobs.mission_stage_id
is 'Nullable stage-attempt link. One executable job belongs to at most one stage attempt.';
